# Generated by Django 6.0.5 on 2026-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role_contactmessage_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('application', 'Application'), ('bookmark', 'Bookmark'), ('profile', 'Profile'), ('security', 'Security'), ('support', 'Support')], max_length=20),
        ),
    ]
