version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: devhire-db
    environment:
      POSTGRES_DB: devhire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devhire"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devhire-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=django-insecure-tu7$$ym+ahg0u+4_8etf@@z_s!ndys#%x2*9#5-fo^ror@!nu*!
      - DEBUG=True
      - DB_NAME=devhire
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devhire-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
