# Generated by Django 6.0.5 on 2026-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
